# Generated by Django 4.1.4 on 2023-01-09 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('category', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('category', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('category', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MentorText',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2023, 1, 9, 6, 47, 55, 883001, tzinfo=datetime.timezone.utc))),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbConnector.skill')),
            ],
        ),
    ]
