# Generated by Django 4.1.4 on 2023-01-09 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbConnector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentortext',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 6, 53, 22, 991258, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mentortext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metric',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
